version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    container_name: currency-bank-api-c
    image: currency-bank-api-i
    restart: always
    networks:
      - currency-exchange

networks:
  currency-exchange: